# Dialect-specific keywords for SQL dialects

[base]
keyword_count = 307

[bigquery]
unique_keywords = ["ANY TYPE", "BEGIN TRANSACTION", "BYTEINT", "BYTES", "CURRENT_DATETIME", "DECLARE", "ELSEIF", "EXCEPTION", "EXPORT", "FLOAT64", "FOR SYSTEM_TIME", "LOOP", "MODEL", "NOT DETERMINISTIC", "RECORD", "REPEAT", "WHILE"]
total_keywords = 321

[clickhouse]
unique_keywords = [".:", "AGGREGATEFUNCTION", "ATTACH", "DATE32", "DATETIME64", "DICTIONARY", "DYNAMIC", "ENUM16", "ENUM8", "EXCHANGE", "FINAL", "FIXEDSTRING", "FLOAT32", "FLOAT64", "GLOBAL", "IPV4", "IPV6", "LINESTRING", "LOWCARDINALITY", "MULTILINESTRING", "MULTIPOLYGON", "NESTED", "NOTHING", "POINT", "POLYGON", "PREWHERE", "RING", "SAMPLE", "SIMPLEAGGREGATEFUNCTION", "SYSTEM", "TUPLE", "UINT16", "UINT32", "UINT64", "UINT8"]
total_keywords = 341

[databricks]
unique_keywords = ["ADD ARCHIVE", "ADD ARCHIVES", "ADD FILE", "ADD FILES", "ADD JAR", "ADD JARS", "MINUS", "MSCK REPAIR", "REFRESH", "SERDEPROPERTIES", "TIMESTAMP AS OF", "VERSION AS OF", "VOID"]
total_keywords = 320

[doris]
unique_keywords = ["@@", "CHARSET", "DISTINCTROW", "FORCE", "IGNORE", "KEY", "LOCK TABLES", "MEMBER OF", "MOD", "SEPARATOR", "SERIAL", "SIGNED", "SIGNED INTEGER", "SOUNDS LIKE", "START", "UNLOCK TABLES", "UNSIGNED", "UNSIGNED INTEGER", "YEAR", "_ARMSCII8", "_ASCII", "_BIG5", "_BINARY", "_CP1250", "_CP1251", "_CP1256", "_CP1257", "_CP850", "_CP852", "_CP866", "_CP932", "_DEC8", "_EUCJPMS", "_EUCKR", "_GB18030", "_GB2312", "_GBK", "_GEOSTD8", "_GREEK", "_HEBREW", "_HP8", "_KEYBCS2", "_KOI8R", "_KOI8U", "_LATIN1", "_LATIN2", "_LATIN5", "_LATIN7", "_MACCE", "_MACROMAN", "_SJIS", "_SWE7", "_TIS620", "_UCS2", "_UJIS", "_UTF16", "_UTF16LE", "_UTF32", "_UTF8", "_UTF8MB3", "_UTF8MB4"]
total_keywords = 368

[duckdb]
unique_keywords = ["**", "//", "<@", "@>", "ATTACH", "BITSTRING", "DETACH", "FORCE", "INSTALL", "LOGICAL", "MACRO", "ONLY", "PIVOT_WIDER", "POSITIONAL", "RESET", "SIGNED", "SUMMARIZE", "TIMESTAMP_MS", "TIMESTAMP_NS", "TIMESTAMP_S", "TIMESTAMP_US", "UBIGINT", "UINTEGER", "USMALLINT", "UTINYINT", "^@"]
total_keywords = 332

[hive]
unique_keywords = ["ADD ARCHIVE", "ADD ARCHIVES", "ADD FILE", "ADD FILES", "ADD JAR", "ADD JARS", "MINUS", "MSCK REPAIR", "REFRESH", "SERDEPROPERTIES", "TIMESTAMP AS OF", "VERSION AS OF"]
total_keywords = 319

[mysql]
unique_keywords = ["@@", "CHARSET", "DISTINCTROW", "FORCE", "IGNORE", "KEY", "LOCK TABLES", "MEMBER OF", "MOD", "SEPARATOR", "SERIAL", "SIGNED", "SIGNED INTEGER", "SOUNDS LIKE", "START", "UNLOCK TABLES", "UNSIGNED", "UNSIGNED INTEGER", "YEAR", "_ARMSCII8", "_ASCII", "_BIG5", "_BINARY", "_CP1250", "_CP1251", "_CP1256", "_CP1257", "_CP850", "_CP852", "_CP866", "_CP932", "_DEC8", "_EUCJPMS", "_EUCKR", "_GB18030", "_GB2312", "_GBK", "_GEOSTD8", "_GREEK", "_HEBREW", "_HP8", "_KEYBCS2", "_KOI8R", "_KOI8U", "_LATIN1", "_LATIN2", "_LATIN5", "_LATIN7", "_MACCE", "_MACROMAN", "_SJIS", "_SWE7", "_TIS620", "_UCS2", "_UJIS", "_UTF16", "_UTF16LE", "_UTF32", "_UTF8", "_UTF8MB3", "_UTF8MB4"]
total_keywords = 368

[oracle]
unique_keywords = ["(+)", "BINARY_DOUBLE", "BINARY_FLOAT", "BULK COLLECT INTO", "COLUMNS", "MATCH_RECOGNIZE", "MINUS", "ORDER SIBLINGS BY", "SAMPLE", "START", "TOP"]
total_keywords = 318

[postgres]
unique_keywords = ["#-", "<@", "?&", "?|", "@>", "@@", "BIGSERIAL", "CONSTRAINT TRIGGER", "CSTRING", "DECLARE", "DO", "EXEC", "HSTORE", "MONEY", "NAME", "OID", "ONLY", "OPERATOR", "REFRESH", "REGCLASS", "REGCOLLATION", "REGCONFIG", "REGDICTIONARY", "REGNAMESPACE", "REGOPER", "REGOPERATOR", "REGPROC", "REGPROCEDURE", "REGROLE", "REGTYPE", "REINDEX", "RESET", "SERIAL", "SMALLSERIAL", "XML", "|/", "||/", "~"]
total_keywords = 343

[presto]
unique_keywords = ["DEALLOCATE PREPARE", "DESCRIBE INPUT", "DESCRIBE OUTPUT", "HYPERLOGLOG", "IPADDRESS", "IPPREFIX", "MATCH_RECOGNIZE", "RESET SESSION", "START", "TDIGEST"]
total_keywords = 315

[redshift]
unique_keywords = ["#-", "(+)", "<@", "?&", "?|", "@>", "@@", "BIGSERIAL", "BINARY VARYING", "CONSTRAINT TRIGGER", "CSTRING", "DECLARE", "DO", "EXEC", "HLLSKETCH", "HSTORE", "MINUS", "MONEY", "NAME", "OID", "ONLY", "OPERATOR", "REFRESH", "REGCLASS", "REGCOLLATION", "REGCONFIG", "REGDICTIONARY", "REGNAMESPACE", "REGOPER", "REGOPERATOR", "REGPROC", "REGPROCEDURE", "REGROLE", "REGTYPE", "REINDEX", "RESET", "SERIAL", "SMALLSERIAL", "SUPER", "TOP", "UNLOAD", "VARBYTE", "XML", "|/", "||/", "~"]
total_keywords = 350

[snowflake]
unique_keywords = ["BYTEINT", "FILE FORMAT", "FILE://", "GET", "MATCH_CONDITION", "MATCH_RECOGNIZE", "MINUS", "NCHAR VARYING", "PUT", "REMOVE", "RM", "SAMPLE", "SEMANTIC VIEW", "SQL_DOUBLE", "SQL_VARCHAR", "STAGE", "STORAGE INTEGRATION", "STREAMLIT", "TAG", "TIMESTAMP_TZ", "TOP", "WAREHOUSE"]
total_keywords = 328

[spark]
unique_keywords = ["ADD ARCHIVE", "ADD ARCHIVES", "ADD FILE", "ADD FILES", "ADD JAR", "ADD JARS", "MINUS", "MSCK REPAIR", "REFRESH", "SERDEPROPERTIES", "TIMESTAMP AS OF", "VERSION AS OF"]
total_keywords = 319

[sqlite]
unique_keywords = ["ATTACH", "DETACH", "INDEXED BY", "MATCH"]
total_keywords = 310

[starrocks]
unique_keywords = ["@@", "CHARSET", "DISTINCTROW", "FORCE", "IGNORE", "KEY", "LARGEINT", "LOCK TABLES", "MEMBER OF", "MOD", "SEPARATOR", "SERIAL", "SIGNED", "SIGNED INTEGER", "SOUNDS LIKE", "START", "UNLOCK TABLES", "UNSIGNED", "UNSIGNED INTEGER", "YEAR", "_ARMSCII8", "_ASCII", "_BIG5", "_BINARY", "_CP1250", "_CP1251", "_CP1256", "_CP1257", "_CP850", "_CP852", "_CP866", "_CP932", "_DEC8", "_EUCJPMS", "_EUCKR", "_GB18030", "_GB2312", "_GBK", "_GEOSTD8", "_GREEK", "_HEBREW", "_HP8", "_KEYBCS2", "_KOI8R", "_KOI8U", "_LATIN1", "_LATIN2", "_LATIN5", "_LATIN7", "_MACCE", "_MACROMAN", "_SJIS", "_SWE7", "_TIS620", "_UCS2", "_UJIS", "_UTF16", "_UTF16LE", "_UTF32", "_UTF8", "_UTF8MB3", "_UTF8MB4"]
total_keywords = 369

[teradata]
unique_keywords = ["**", "BYTEINT", "COLLECT", "DEL", "EQ", "GE", "GT", "HELP", "INS", "LE", "LOCKING", "LT", "MINUS", "MOD", "NE", "NOT=", "SAMPLE", "SEL", "ST_GEOMETRY", "TOP", "UPD", "^="]
total_keywords = 328

[trino]
unique_keywords = ["DEALLOCATE PREPARE", "DESCRIBE INPUT", "DESCRIBE OUTPUT", "HYPERLOGLOG", "IPADDRESS", "IPPREFIX", "MATCH_RECOGNIZE", "REFRESH", "RESET SESSION", "START", "TDIGEST"]
total_keywords = 316

[mssql]
unique_keywords = ["CLUSTERED INDEX", "DATETIME2", "DATETIMEOFFSET", "DECLARE", "EXEC", "FOR SYSTEM_TIME", "GO", "IMAGE", "MONEY", "NONCLUSTERED INDEX", "NTEXT", "OPTION", "OUTPUT", "PRINT", "PROC", "ROWVERSION", "SMALLDATETIME", "SMALLMONEY", "SQL_VARIANT", "SYSTEM_USER", "TOP", "UNIQUEIDENTIFIER", "UPDATE STATISTICS", "XML"]
total_keywords = 330

